version: '3.8'

services:
  server:
    container_name: Sir-Count-A-Lot
    build:
      context: .
    ports:
      - "7070:7070"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: analytics-db
    image: postgres:latest
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: deinemutterstinkt
      POSTGRES_DB: analytics-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: omega@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db-data:


# Command for Uptime Kuma. Share docker.sock between UK container and all others
#  - /var/run/docker.sock:/var/run/docker.sock