version: '3.8'

services:
  server:
    container_name: Sir-Count-A-Lot
    build:
      context: .
    ports:
      - "7070:7070"
    env_file:
      - .env
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: analytics-db
    image: postgres:latest
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: analytics-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASSWORD}
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db-data:
